In [45]:
import pandas as pd 

from sklearn import datasets
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics  

iris = datasets.load_iris()

print(iris.target_names) 
print(iris.feature_names) 
print(iris.data[0:5]) 

print(iris.target) 


data=pd.DataFrame({ 

    'sepal length':iris.data[:,0], 

    'sepal width':iris.data[:,1], 

    'petal length':iris.data[:,2], 

    'petal width':iris.data[:,3], 
 
    'species':iris.target 

}) 

data.head() 


# X=data[['sepal length', 'sepal width', 'petal length', 'petal width']]  # Features 

X = data.drop("species", axis = 1)

y=data['species']  # Labels 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)



clf=RandomForestClassifier(n_estimators=100)  

clf.fit(X_train,y_train) 

y_pred=clf.predict(X_test) 


print("Accuracy:",metrics.accuracy_score(y_test, y_pred)) 

 

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Accuracy: 0.9777777777777777


In [69]:
# Practice Random Forest
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.metrics import confusion_matrix

ds = datasets.load_iris()

print(ds.feature_names)
print(ds.target_names)
print(ds.data[0:5])



data = pd.DataFrame({
        'sepal length (cm)': iris.data[:,0],
        'sepal width (cm)': iris.data[:,1],
        'petal length (cm)': iris.data[:,2],
        'petal width (cm)':iris.data[:,3],
        'species': iris.target
})

x = data.drop("species", axis = 1)


from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 109)

classifier = RandomForestClassifier()


classifier.fit(x_train, y_train) 

y_pred=classifier.predict(x_test)

classifier.accuracy_score()
# help(train_test_split)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


AttributeError: 'RandomForestClassifier' object has no attribute 'accuracy_score'